### ISSUE TITLE
Package not published/found on npm public registry

### ISSUE THREAD

**Issue by josemussa** [mixer/webpack-bundle-compare#2]
I really like this idea! I was planning to implement it for a project and I found out that NPM throws a `404` when I try to install it, perhaps it's published under another namespace? or not published at all?

https://www.npmjs.com/package/@mixer/webpack-bundle-compare

```sh
$ npm i @mixer/webpack-bundle-compare --save-dev
npm ERR! code E404
npm ERR! 404 Not Found: @mixer/webpack-bundle-compare@latest
```

**Comment by connor4312** [comment]
Thanks for opening an issue! This has now been published.
