### ISSUE TITLE
Support for uploading stats file from local file system

### ISSUE THREAD

**Issue by christiango** [mixer/webpack-bundle-compare#3]
Thanks for sharing this awesome tool! We've already integrated it into our build pipeline for Office Online.

One thing that would be great would be the ability to choose files from the local file system for comparison, similar to what [webpack analyse](http://webpack.github.io/analyse/) does (though they don't support the URL blob upload). The scenario here would be for developers wanting to see the impact of a change in a local branch before publishing a PR.

Was thinking that the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) API should make this possible

**Comment by connor4312** [comment]
Definitely a good idea, something I have been intending to do. Happy to accept PRs for it, otherwise I'll try to get to in within the next few work days.

**Comment by christiango** [comment]
Awesome! It's not something we'd want urgently. I'll let you know if I'm able to find some time to give it a crack myself in the next few days.

**Comment by christiango** [comment]
Thanks for adding this feature!

**Comment by connor4312** [comment]
no problem, thanks for the suggestion :)
